export GPG_TTY=$(tty)

function hm-nukeapps() {
  rm -rf "$HOME/Applications/Home Manager Apps"
}

function hm-firstswitch() {
  nix build "$NIXHOSTS#darwinConfigurations.$(hostname -s).system" &&
  hm-nukeapps &&
  sudo ./result/sw/bin/darwin-rebuild --show-trace --flake "$NIXHOSTS" switch
}

function hm-build() {
  sudo darwin-rebuild --show-trace --flake "$NIXHOSTS#$(hostname -s)" build
}

function _hm-doswitch() {
  sudo darwin-rebuild --show-trace --flake "$NIXHOSTS#$(hostname -s)" switch
}

function hm-switch() {
  local with_build=${1:-nobuild}

  if [ "$with_build" = "build" ]; then
    hm-build && hm-nukeapps && _hm-doswitch
  else
    echo "INFO: to build first: sudo hm-switch build" >&2
    hm-nukeapps && _hm-doswitch
  fi
}
