# Alacritty won't quit on command-q:
alias noquit="defaults write org.alacritty NSUserKeyEquivalents -dict-add \"Quit alacritty\" -string \"@~q\""

function setgpgprogram {
  git config --global gpg.program $(which gpg)
}

function hm-build() {
  nixos-rebuild --show-trace --flake "$NIXHOSTS#$(hostname -s)" build
}

function _hm-doswitch() {
  sudo nixos-rebuild --show-trace --flake "$NIXHOSTS#$(hostname -s)" switch
}

function hm-switch() {
  local with_build=${1:-nobuild}

  if [ "$with_build" = "build" ]; then
    hm-build && _hm-doswitch
  else
    echo "INFO: to build first: hm-switch build" >&2
    _hm-doswitch
  fi
}
