export GIT_PROMPT_THEME=BlackOrWhite
export GIT_PROMPT_FETCH_REMOTE_STATUS=0

if [ -n "$IN_NIX_SHELL" ]; then
  echo "In nix shell."
fi

export EDITOR=vim

# General usefulness:
alias is="env | grep -i NIX_SHELL"
alias gs="git status"
alias vim="nvim"
alias rmswp="find . -name *.swp | xargs rm"
alias strl="history -d $((HISTCMD-1))"

# Ruby:
alias be="bundle exec"
alias bert="bundle exec rake"

# This must be done from within the cloned nixhosts dir:
alias initial-nixhost-switch="rm -rf ~/Applications/Home\ Manager\ Apps && nix build \".#darwinConfigurations.$(hostname -s).system\" && ./result/sw/bin/darwin-rebuild switch --flake ."

# This can be done anywhere:
alias nixhost-switch="rm -rf ~/Applications/Home\ Manager\ Apps && nix build \".#darwinConfigurations.$(hostname -s).system\" && darwin-rebuild switch --flake ."

# source $HOME/.nix-profile/share/git/contrib/completion/git-prompt.sh
# source $HOME/.nix-profile/share/git/contrib/completion/git-completion.bash

# disable freeze on ctrl-s
stty -ixon

eval "$(direnv hook zsh)"

unsetopt AUTO_MENU

function setgpgprogram {
  git config --global gpg.program $(which gpg)
}


if [ -f ~/.zshrc.local ]; then
  source ~/.zshrc.local
fi

