export GIT_PROMPT_THEME=BlackOrWhite
export GIT_PROMPT_FETCH_REMOTE_STATUS=0

if [ -n "$IN_NIX_SHELL" ]; then
  echo "In nix shell."
fi

export EDITOR=vim

# Alacritty won't quit on command-q:
alias noquit="defaults write org.alacritty NSUserKeyEquivalents -dict-add \"Quit alacritty\" -string \"@~q\""

# General usefulness:
alias is="env | grep -i NIX_SHELL"
alias gs="git status"
alias vim="nvim"
alias rmswp="find . -name *.swp | xargs rm"
alias strl="history -d $((HISTCMD-1))"

# Ruby:
alias be="bundle exec"
alias bert="bundle exec rake"

# This must be done from within the cloned nixhosts dir:
function initial-hm-switch() {
  rm -rf "$HOME/Applications/Home Manager Apps" &&
  echo "nixhosts: $NIXHOSTS" &&
  nix build "$NIXHOSTS#darwinConfigurations.$(hostname -s).system" &&
  ./result/sw/bin/darwin-rebuild switch --flake "$NIXHOSTS"
}

# This can be done anywhere:
function hm-switch() {
  rm -rf "$HOME/Applications/Home Manager Apps" &&
  echo "nixhosts: $NIXHOSTS" &&
  nix build "$NIXHOSTS#darwinConfigurations.$(hostname -s).system" &&
  darwin-rebuild switch --flake "$NIXHOSTS"
}

function setgpgprogram {
  git config --global gpg.program $(which gpg)
}

# source $HOME/.nix-profile/share/git/contrib/completion/git-prompt.sh
# source $HOME/.nix-profile/share/git/contrib/completion/git-completion.bash

# disable freeze on ctrl-s
stty -ixon

eval "$(direnv hook zsh)"

unsetopt AUTO_MENU
unsetopt correct
setopt NO_MENU_COMPLETE BASH_AUTO_LIST

unalias find

if [ -f ~/.zshrc.local ]; then
  source ~/.zshrc.local
fi

