# Alacritty won't quit on command-q:
alias noquit="defaults write org.alacritty NSUserKeyEquivalents -dict-add \"Quit alacritty\" -string \"@~q\""

function setgpgprogram {
  git config --global gpg.program $(which gpg)
}

