[
  ./dconf.nix
  ./env.nix
  ./gnome.nix
  ./meta.nix
  ./packages.nix
  ./programs/nushell
  ./programs/zsh
  ./programs/alacritty.nix
  ./programs/browser.nix
  ./programs/ssh.nix
  ./services.nix
]
