cask_args appdir: "~/Applications/Homebrew"

cask "bitwarden"
cask "gpg-suite-no-mail"
cask "nordvpn"

cask "keycastr"

cask "istat-menus"
cask "fluor"

cask "keyboardcleantool"

cask "obsidian"
cask "karabiner-elements"

cask "keybase"
