export EDITOR=vim

# Test true color support

function test-truecolor-support() {
  awk 'BEGIN{
      s="/\\/\\/\\/\\/\\"; s=s s s s s s s s;
      for (colnum = 0; colnum<77; colnum++) {
          r = 255-(colnum*255/76);
          g = (colnum*510/76);
          b = (colnum*255/76);
          if (g>255) g = 510-g;
          printf "\033[48;2;%d;%d;%dm", r,g,b;
          printf "\033[38;2;%d;%d;%dm", 255-r,255-g,255-b;
          printf "%s\033[0m", substr(s,colnum+1,1);
      }
      printf "\n";
  }'
}

# disable freeze on ctrl-s
stty -ixon

if [ -f ~/.zshrc.local ]; then
  source ~/.zshrc.local
fi


setopt HIST_FCNTL_LOCK
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt SHARE_HISTORY
setopt BASH_AUTO_LIST
setopt LIST_AMBIGUOUS
setopt GLOBDOTS

unsetopt AUTO_PUSHD
unsetopt AUTO_MENU
unsetopt MENU_COMPLETE
unsetopt AUTO_PARAM_SLASH
unsetopt AUTOCD
unsetopt APPEND_HISTORY
unsetopt EXTENDED_HISTORY
